---
title: "2. Quality control"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)

```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}

here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data 



# Save Seurat object

qs::qsave is much faster than save RDS

```{r,echo=F,eval=T,message=FALSE,warning=F}
qs::qsave(combined, "combined.qsave") 
#combined <- qs::qread('combined.qsave')

```

# Alternatively, save RDS

```{r,echo=F,eval=T,message=FALSE,warning=F}
saveRDS(combined, "combined.rds")
```

```{r,echo=F,eval=T,message=FALSE,warning=F}

```

```{r,echo=F,eval=T,message=FALSE,warning=F}

```

```{r,echo=F,eval=T,message=FALSE,warning=F}

```

```{r,echo=F,eval=T,message=FALSE,warning=F}

```

```{r,echo=F,eval=T,message=FALSE,warning=F}

```

# Session info

```{r,echo=F,eval=T,message=FALSE,warning=F}
sessionInfo()
```

