---
title: "Data integration"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)

```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}

here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}

####

#combined <- readRDS("combined.rds")
combined <- qs::qread('combined_qc.qsave')
####

```

# Integration

```{r,echo=F,eval=T,message=F,warning=F,error=F}

combine.list <- SplitObject(combined, split.by = "orig.ident")
combine.list <- lapply(
  X = combine.list,
  FUN = function(x) {
    x <- NormalizeData(x)
    x <-
      FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
  }
)
combine.anchors <-
  FindIntegrationAnchors(object.list = combine.list, dims = 1:30)
combined <- IntegrateData(anchorset = combine.anchors, dims = 1:30)


```

# Dimension reduction

```{r,echo=F,eval=F,message=F,warning=F,error=F}

DefaultAssay(combined) <- "integrated"
combined <- ScaleData(combined, verbose = FALSE)
combined <- RunPCA(combined, npcs = 30, verbose = FALSE)
combined <- RunUMAP(combined, reduction = "pca", dims = 1:30)
combined <- FindNeighbors(combined, reduction = "pca", dims = 1:30)
combined <- FindClusters(combined, resolution = 0.3)

```

```{r,echo=F,eval=F,message=F,warning=F,error=F}

```


```{r,echo=F,eval=F,message=F,warning=F,error=F}

```

```{r,echo=F,eval=F,message=F,warning=F,error=F}

```

```{r,echo=F,eval=F,message=F,warning=F,error=F}

```

```{r,echo=F,eval=T,message=FALSE,warning=F}
# Save Seurat object
# qs::qsave is much faster than save RDS

qs::qsave(combined, "combined.qsave") 
#combined <- qs::qread('combined.qsave')

```

```{r,echo=F,eval=F,message=F,warning=F,error=F}
# Manually save the rds, do not save on knitr
saveRDS(combined, "combined.rds")
```

