---
title: "4. Cell type annotation"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
library(fgsea)
library(msigdbr)
library(monocle3)
library(batchelor)
library(Matrix.utils)


```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}
here::i_am("4_cell_type_annotation.Rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("functions.R")

combined <- qs::qread('combined.qsave')

DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$seurat_clusters

custom_color <-
  as.character(palette36.colors(36)[-2])[1:length(levels(Idents(combined)))]
two_color <- c('#C0C0C0', '#B00D23')

provided_marker <- read_csv("provided_marker.csv") %>%
  mutate(cell_type = factor(cell_type))

provided_marker
```

# Identify cell clusters


```{r,echo=F,eval=F,message=FALSE,warning=F}

dbs <-
  c(
    "GO_Molecular_Function_2018",
    "GO_Cellular_Component_2018",
    "GO_Biological_Process_2018",
    "KEGG_2019_Human"
  )

DefaultAssay(combined) <- "RNA"
#combined <- FindClusters(combined, resolution = 0.5)

```


```{r,echo=F,eval=T,message=T,warning=F,error=F}

Idents(combined) <- combined$orig.ident
DimPlot(combined, reduction = "umap", cols = as.vector(palette36.colors(36)[-2]),label = T)

#DimPlot(combined, reduction = "tsne", cols = as.vector(palette36.colors(36)[-2]),label = T)

```


```{r,echo=F,eval=T,message=F,warning=F,error=F, fig.width=12,fig.height=8}

Idents(combined) <- combined$seurat_clusters

p2 <-
  DimPlot(
    combined,
    reduction = "umap",
    split.by = "condition",
    cols = as.vector(palette36.colors(36)[-2]),
    ncol = 2,
    pt.size = 0.7
  )

png(
  paste("cluster_split_by_condition.png", sep = ""),
  width = 3000,
  height = 1500,
  res = 300
)

p2
dev.off()
p2

```

## Split by samples

Number of cells for each cluster:

```{r,echo=F,eval=T,message=F,warning=F,error=F, fig.width=12,fig.height=8}

table(combined$orig.ident, combined$seurat_clusters)

```


```{r,echo=F,eval=T,message=F,warning=F,error=F, fig.width=8,fig.height=16}



p3 <-
  DimPlot(
    combined,
    reduction = "umap",
    group.by = "seurat_clusters",
    split.by = "orig.ident",
    cols = as.vector(palette36.colors(36)[-2]),
    ncol = 6,
    pt.size = 0.6
  )

png(
  paste("cluster_split_by_sample.png", sep = ""),
  width = 6000,
  height = 2000,
  res = 300
)

p3
dev.off()
p3

```


# Annotate by cell type markers

Criteria:

- Having all marker gene expression > 0.1
- If a cell matches multiple cell type based on marker expression, use the cell type label with the highest expression

```{r,echo=F,eval=F,message=FALSE,warning=F}
#DefaultAssay(combined) <- 'integrated'
Idents(combined) <- combined$orig.ident
DefaultAssay(combined) <- "RNA"

cell_type_range <- seq_along(levels(provided_marker$cell_type))
marker_genes <- unique(provided_marker$gene)
marker_expr <- Seurat::FetchData(object = combined, vars = marker_genes)

# seq_along(levels(provided_marker$cell_type))
for (idx in seq_along(levels(provided_marker$cell_type))) {
  this_ct <- levels(provided_marker$cell_type)[idx]
  
  this_markers <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(gene)
  this_direction <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(direction)
  this_data <- Seurat::FetchData(object = combined, vars = this_markers)
  selected_cells <- rownames(this_data)
  for (k in seq_along(this_markers)) {
    if (this_direction[k] == "pos") {
      this_cells <- this_data %>%
        filter(get(this_markers[k]) >  0.1) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    } else{
      this_cells <- this_data %>%
        filter(get(this_markers[k]) <= 0.1) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    }
  }
  
  selected_cells <- unique(selected_cells)
  this_obj <- combined[, selected_cells]
  
  combined@meta.data$tmp_ct <-
    ifelse(rownames(combined@meta.data) %in% colnames(this_obj),
           "positive",
           "negative")
  
  Idents(combined) <- combined$orig.ident
  this_ct_ident <- gsub(" ", "_", this_ct)
  tmp_ct_index <- which(colnames(combined@meta.data) == 'tmp_ct')
  colnames(combined@meta.data)[tmp_ct_index] <- this_ct_ident

}




```


```{r,echo=F,eval=F,message=F,warning=F,error=F}
qs::qsave(combined,'combined.qsave')
```


```{r,echo=F,eval=T,message=F,warning=F,error=F}

```
